[project]
name = "internshipproject1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.6",
    "django-environ>=0.12.0",
    "django-formtools>=2.5.1",
    "psycopg>=3.2.10",
    "python-dotenv>=1.1.1",
]
