from .application_list import ApplicationListView
from .application_create import ApplicationCreateView, get_requirements_for_specialty
from .application_update import ApplicationUpdateView
from .application_detail import ApplicationDetailView