# Generated by Django 5.2.6 on 2025-10-01 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='applicationbranch',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application', verbose_name='Application'),
        ),
        migrations.AddField(
            model_name='applicationbranch',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='application',
            name='branches',
            field=models.ManyToManyField(through='applications.ApplicationBranch', to='applications.branch', verbose_name='Branches'),
        ),
        migrations.AddField(
            model_name='branch',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.district', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='applicationbranch',
            name='selected_equipment',
            field=models.ManyToManyField(blank=True, to='applications.equipment', verbose_name='Selected Equipment'),
        ),
        migrations.AddField(
            model_name='equipmentrequired',
            name='required_equipment',
            field=models.ManyToManyField(blank=True, to='applications.equipment', verbose_name='Minimum required equipment'),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='applications.region', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='applicationbranch',
            name='selected_specialists',
            field=models.ManyToManyField(blank=True, to='applications.specialist', verbose_name='Selected Specialists'),
        ),
        migrations.AddField(
            model_name='specialistsrequired',
            name='required_specialists',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.specialist', verbose_name='Minimum required specialists'),
        ),
        migrations.AddField(
            model_name='specialistsrequired',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.specialty', verbose_name='Specialty'),
        ),
        migrations.AddField(
            model_name='equipmentrequired',
            name='specialty',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='applications.specialty', verbose_name='Specialty'),
        ),
        migrations.AddField(
            model_name='applicationbranch',
            name='specialties',
            field=models.ManyToManyField(to='applications.specialty', verbose_name='Specialties'),
        ),
        migrations.AlterUniqueTogether(
            name='specialistsrequired',
            unique_together={('specialty', 'required_specialists')},
        ),
    ]
