# Generated by Django 5.2.6 on 2025-10-01 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialistsrequired',
            options={'verbose_name': 'Specialist Required', 'verbose_name_plural': 'Specialists Required'},
        ),
        migrations.RemoveField(
            model_name='equipmentrequired',
            name='min_count',
        ),
        migrations.RemoveField(
            model_name='equipmentrequired',
            name='required_equipment',
        ),
        migrations.CreateModel(
            name='EquipmentRequiredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_count', models.PositiveIntegerField(default=1, verbose_name='Minimum count')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.equipment', verbose_name='Equipment')),
                ('equipment_required', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='applications.equipmentrequired', verbose_name='Equipment Required')),
            ],
            options={
                'verbose_name': 'Equipment Required Item',
                'verbose_name_plural': 'Equipment Required Items',
                'unique_together': {('equipment_required', 'equipment')},
            },
        ),
    ]
